In [7]:

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Correct path to your data folder
DATA_DIR = Path(r"C:\Users\Menzi\Desktop\GeoMet-Flotation-Analysis\Data")

# Load the three datasets
flotation = pd.read_csv(DATA_DIR / "flotation.csv")
comminution = pd.read_csv(DATA_DIR / "comminution.csv")
drillholes = pd.read_csv(DATA_DIR / "drillholes.csv")

print("All datasets loaded successfully!")
print("Flotation:", flotation.shape)
print("Comminution:", comminution.shape)
print("Drill holes:", drillholes.shape)

All datasets loaded successfully!
Flotation: (53, 26)
Comminution: (60, 28)
Drill holes: (2000, 22)

In [8]:

datasets = {
    "Flotation": flotation,
    "Comminution": comminution,
    "Drill holes": drillholes
}

for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(f"{name.upper()} DATASET")
    print("=" * 70)

    print(f"Rows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]}")

    print("\nColumn names and data types:")
    display(df.dtypes.rename("Data type").to_frame())

    print("\nFirst five rows:")
    display(df.head())

    print("\nMissing values per column:")
    display(df.isna().sum().to_frame("Missing values"))

======================================================================
FLOTATION DATASET
======================================================================
Rows: 53
Columns: 26

Column names and data types:

       Data type
HOLEID     int64
X        float64
Y        float64
Z        float64
fr       float64
xr       float64
LCT      float64
Ag ppm   float64
Al ppm   float64
Au ppm   float64
C ppm    float64
Ca ppm   float64
Cl ppm   float64
Cu ppm   float64
F ppm    float64
Fe ppm   float64
K ppm    float64
Mg ppm   float64
Mn ppm   float64
Na ppm   float64
P ppm    float64
S ppm    float64
Si ppm   float64
Th ppm   float64
Ti ppm   float64
U ppm    float64

First five rows:

,HOLEID,X,Y,Z,fr,xr,LCT,Ag ppm,Al ppm,Au ppm,...,K ppm,Mg ppm,Mn ppm,Na ppm,P ppm,S ppm,Si ppm,Th ppm,Ti ppm,U ppm
0,1,552.477467,-532.30374,205.5292,0.283015,0.018674,0.878482,3.868453,52663.89,0.559473,...,22420.69,5597.62,4533.00,2545.81,460.00,2190.0,185170.63,3.00000,3279.92,10.313938
1,2,745.774899,-279.77297,283.2592,0.164382,0.032202,0.942708,1.163020,59961.45,0.145705,...,12681.64,21675.07,567.67,17661.13,460.00,2515.0,297536.61,32.56262,1725.74,31.213873
2,5,200.349851,-520.86427,315.4624,0.217624,0.031381,0.875660,4.438694,57708.76,0.317735,...,8069.68,11989.16,3502.83,472.30,814.66,4260.0,186907.60,3.00000,3739.87,19.530516
3,6,494.372077,-528.86816,311.2195,0.223851,0.022228,0.912880,2.720497,61648.61,0.455832,...,15200.58,15857.07,4735.52,6325.94,790.56,2710.0,185147.18,3.00000,4598.24,9.784736
4,6,500.224749,-513.62142,266.3491,0.200504,0.054880,0.937375,2.800237,33358.01,2.116526,...,4545.44,5405.55,981.06,14708.27,983.61,9830.0,128867.71,3.00000,2089.48,32.869081

Missing values per column:

        Missing values
HOLEID               0
X                    0
Y                    0
Z                    0
fr                   0
xr                   0
LCT                  1
Ag ppm               0
Al ppm               0
Au ppm               0
C ppm                0
Ca ppm               0
Cl ppm               4
Cu ppm               0
F ppm                0
Fe ppm               0
K ppm                0
Mg ppm               0
Mn ppm               0
Na ppm               0
P ppm                0
S ppm                0
Si ppm               0
Th ppm               0
Ti ppm               0
U ppm                0

======================================================================
COMMINUTION DATASET
======================================================================
Rows: 60
Columns: 28

Column names and data types:

                    Data type
HOLEID                  int64
X                     float64
Y                     float64
Z                     float64
th1                   float64
th2                   float64
th3                   float64
F80                   float64
P80                   float64
M                     float64
A                     float64
Al ppm                float64
C ppm                 float64
Ca ppm                float64
Carbono Grafite ppm   float64
Cl ppm                float64
Cu ppm                float64
F ppm                 float64
Fe ppm                float64
K ppm                 float64
Mg ppm                float64
Mn ppm                float64
Na ppm                float64
P ppm                 float64
S ppm                 float64
Si ppm                float64
Th ppm                float64
U ppm                 float64

First five rows:

,HOLEID,X,Y,Z,th1,th2,th3,F80,P80,M,...,Fe ppm,K ppm,Mg ppm,Mn ppm,Na ppm,P ppm,S ppm,Si ppm,Th ppm,U ppm
0,120,342.445175,-382.72032,337.81,0.042350,0.176221,0.402691,2174.237514,97.105344,0.808429,...,287065.387485,20113.863021,6621.980599,6925.555200,155.000000,230.000000,2790.0,183035.003376,3.0,10.454775
1,121,127.095175,-88.51032,251.62,0.038470,0.191321,0.410466,2188.542916,115.508073,0.855116,...,229643.336529,28938.287402,6324.065197,3112.176414,388.315945,230.000000,724.0,226433.365292,3.0,3.646887
2,122,186.685175,-344.57032,334.54,0.030830,0.151751,0.326471,1983.825716,102.098877,0.973609,...,239465.402844,22656.358382,6925.118483,3850.236967,1608.487476,230.000000,1055.0,215387.677725,3.0,8.505810
3,123,297.195175,-219.90032,266.55,0.031255,0.196491,0.419411,1969.796571,116.762223,1.047199,...,272844.696970,25535.603113,6490.530303,6814.393939,345.348249,230.000000,1430.0,194772.727273,3.0,6.233930
4,124,365.475175,-180.95032,264.01,0.038660,0.168131,0.382681,2222.819841,100.826620,1.155266,...,238553.639847,26901.626794,8932.950192,3852.490421,1686.076555,492.337165,745.0,205308.429119,3.0,3.286489

Missing values per column:

                     Missing values
HOLEID                            0
X                                 0
Y                                 0
Z                                 0
th1                               0
th2                               0
th3                               0
F80                               0
P80                               0
M                                 0
A                                 0
Al ppm                            0
C ppm                             0
Ca ppm                            0
Carbono Grafite ppm              12
Cl ppm                            1
Cu ppm                            0
F ppm                             0
Fe ppm                            0
K ppm                             0
Mg ppm                            0
Mn ppm                            0
Na ppm                            0
P ppm                             0
S ppm                             0
Si ppm                            0
Th ppm                           34
U ppm                             2

======================================================================
DRILL HOLES DATASET
======================================================================
Rows: 2,000
Columns: 22

Column names and data types:

       Data type
HOLEID     int64
X        float64
Y        float64
Z        float64
Ag ppm   float64
Al ppm   float64
Au ppm   float64
C ppm    float64
Ca ppm   float64
Cl ppm   float64
Cu ppm   float64
F ppm    float64
Fe ppm   float64
K ppm    float64
Mg ppm   float64
Mn ppm   float64
Na ppm   float64
P ppm    float64
Pb ppm   float64
S ppm    float64
Th ppm   float64
U ppm    float64

First five rows:

,HOLEID,X,Y,Z,Ag ppm,Al ppm,Au ppm,C ppm,Ca ppm,Cl ppm,...,Fe ppm,K ppm,Mg ppm,Mn ppm,Na ppm,P ppm,Pb ppm,S ppm,Th ppm,U ppm
0,1,559.725175,-513.31032,252.82,0.64,42900.0,1.04,800.0,15100.0,1985.11,...,351800.0,8300.0,6700.0,1550.44,17800.0,1094.44,20.68,6100.0,2.20,31.37
1,1,558.955175,-515.23032,246.87,0.20,70100.0,0.06,400.0,8300.0,5046.67,...,215200.0,24600.0,10400.0,2717.78,9700.0,960.00,3.89,600.0,5.02,4.78
2,1,557.225175,-519.61032,233.37,3.44,14000.0,2.02,900.0,12600.0,1467.20,...,462600.0,4200.0,3200.0,1216.52,4300.0,937.20,20.64,11700.0,1.41,30.57
3,1,555.375175,-524.30032,218.92,4.88,19600.0,3.43,900.0,4500.0,606.79,...,444900.0,6100.0,4700.0,2504.82,2600.0,1024.29,18.00,11000.0,1.43,34.46
4,1,553.825175,-528.21032,206.94,1.25,54300.0,0.50,2500.0,5600.0,3598.69,...,288600.0,22300.0,4600.0,4249.90,1900.0,369.39,6.89,2200.0,3.28,10.33

Missing values per column:

        Missing values
HOLEID               0
X                    0
Y                    0
Z                    0
Ag ppm               0
Al ppm               0
Au ppm               0
C ppm                0
Ca ppm               0
Cl ppm               0
Cu ppm               0
F ppm                0
Fe ppm               0
K ppm                0
Mg ppm               0
Mn ppm               0
Na ppm               0
P ppm                0
Pb ppm               0
S ppm                0
Th ppm               0
U ppm                0

In [10]:

for name, df in datasets.items():
    print(f"\n{name.upper()} ({len(df.columns)} columns)")
    print("-" * 40)

    for col in df.columns:
        print(col)

FLOTATION (26 columns)
----------------------------------------
HOLEID
X
Y
Z
fr
xr
LCT
Ag ppm
Al ppm
Au ppm
C ppm
Ca ppm
Cl ppm
Cu ppm
F ppm
Fe ppm
K ppm
Mg ppm
Mn ppm
Na ppm
P ppm
S ppm
Si ppm
Th ppm
Ti ppm
U ppm

COMMINUTION (28 columns)
----------------------------------------
HOLEID
X
Y
Z
th1
th2
th3
F80
P80
M
A
Al ppm
C ppm
Ca ppm
Carbono Grafite ppm
Cl ppm
Cu ppm
F ppm
Fe ppm
K ppm
Mg ppm
Mn ppm
Na ppm
P ppm
S ppm
Si ppm
Th ppm
U ppm

DRILL HOLES (22 columns)
----------------------------------------
HOLEID
X
Y
Z
Ag ppm
Al ppm
Au ppm
C ppm
Ca ppm
Cl ppm
Cu ppm
F ppm
Fe ppm
K ppm
Mg ppm
Mn ppm
Na ppm
P ppm
Pb ppm
S ppm
Th ppm
U ppm

Checking whether the numbers from these csv files can be linked or not

In [11]:

# Check identifiers and duplicate records
for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(name.upper())

    print("Total rows:", len(df))
    print("Unique HOLEID values:", df["HOLEID"].nunique())
    print("Missing HOLEID values:", df["HOLEID"].isna().sum())
    print("Duplicate complete rows:", df.duplicated().sum())
    print("Repeated HOLEID rows:", df["HOLEID"].duplicated().sum())

==================================================
FLOTATION
Total rows: 53
Unique HOLEID values: 29
Missing HOLEID values: 0
Duplicate complete rows: 0
Repeated HOLEID rows: 24

==================================================
COMMINUTION
Total rows: 60
Unique HOLEID values: 37
Missing HOLEID values: 0
Duplicate complete rows: 0
Repeated HOLEID rows: 23

==================================================
DRILL HOLES
Total rows: 2000
Unique HOLEID values: 119
Missing HOLEID values: 0
Duplicate complete rows: 0
Repeated HOLEID rows: 1881

In [12]:

flotation_ids = set(flotation["HOLEID"].dropna())
comminution_ids = set(comminution["HOLEID"].dropna())
drillhole_ids = set(drillholes["HOLEID"].dropna())

print("Flotation IDs also in drill holes:",
      len(flotation_ids & drillhole_ids))

print("Comminution IDs also in drill holes:",
      len(comminution_ids & drillhole_ids))

print("Flotation IDs also in comminution:",
      len(flotation_ids & comminution_ids))

Flotation IDs also in drill holes: 27
Comminution IDs also in drill holes: 23
Flotation IDs also in comminution: 21

In [13]:

# Compare coordinates for HOLEIDs shared between datasets

pairs = [
    ("Flotation", flotation, "Drill holes", drillholes),
    ("Comminution", comminution, "Drill holes", drillholes),
    ("Flotation", flotation, "Comminution", comminution),
]

for name_a, df_a, name_b, df_b in pairs:
    print(f"\n{'=' * 60}")
    print(f"{name_a} vs {name_b}")

    shared_ids = set(df_a["HOLEID"]) & set(df_b["HOLEID"])

    print("Shared HOLEIDs:", len(shared_ids))

    # Show coordinate records for a few shared holes
    sample_ids = sorted(shared_ids)[:5]

    for hole_id in sample_ids:
        print(f"\nHOLEID: {hole_id}")

        print(f"{name_a}:")
        display(
            df_a.loc[
                df_a["HOLEID"] == hole_id,
                ["HOLEID", "X", "Y", "Z"]
            ].head(5)
        )

        print(f"{name_b}:")
        display(
            df_b.loc[
                df_b["HOLEID"] == hole_id,
                ["HOLEID", "X", "Y", "Z"]
            ].head(5)
        )

============================================================
Flotation vs Drill holes
Shared HOLEIDs: 27

HOLEID: 1
Flotation:

    HOLEID           X           Y         Z
0        1  552.477467 -532.303740  205.5292
12       1  549.263567 -540.676239  182.1664

Drill holes:

   HOLEID           X          Y       Z
0       1  559.725175 -513.31032  252.82
1       1  558.955175 -515.23032  246.87
2       1  557.225175 -519.61032  233.37
3       1  555.375175 -524.30032  218.92
4       1  553.825175 -528.21032  206.94

HOLEID: 2
Flotation:

    HOLEID           X          Y         Z
1        2  745.774899 -279.77297  283.2592
13       2  737.619747 -301.01787  223.9768

Drill holes:

    HOLEID           X          Y       Z
15       2  745.345175 -280.60032  280.94
16       2  741.865175 -288.97032  257.64
17       2  738.305175 -297.31032  234.34
18       2  734.705175 -305.65032  211.05
19       2  731.415175 -313.15032  190.52

HOLEID: 3
Flotation:

    HOLEID          X          Y           Z
28       3 -306.22738  311.90928  262.633392
29       3 -310.27390  301.10094  231.504330

Drill holes:

    HOLEID           X          Y       Z
30       3 -304.024825  318.12968  281.09
31       3 -306.424825  311.36968  261.04
32       3 -308.914825  304.69968  241.70
33       3 -311.554825  297.72968  222.02
34       3 -313.374825  293.07968  208.94

HOLEID: 5
Flotation:

    HOLEID           X           Y         Z
2        5  200.349851 -520.864270  315.4624
14       5  211.149327 -492.730677  236.9576

Drill holes:

    HOLEID           X          Y       Z
62       5  198.815175 -524.78032  324.65
63       5  200.565175 -520.24032  311.15
64       5  202.425175 -515.44032  296.82
65       5  204.675175 -509.67032  279.67
66       5  205.785175 -506.81032  271.28

HOLEID: 6
Flotation:

   HOLEID           X          Y         Z
3       6  494.372077 -528.86816  311.2195
4       6  500.224749 -513.62142  266.3491
5       6  506.353202 -497.65626  219.3645
6       6  509.539998 -489.35437  194.9325

Drill holes:

    HOLEID           X          Y       Z
71       6  493.605175 -530.83032  317.10
72       6  494.555175 -528.02032  309.03
73       6  495.235175 -525.99032  303.16
74       6  496.795175 -521.30032  289.63
75       6  499.435175 -513.34032  266.61

============================================================
Comminution vs Drill holes
Shared HOLEIDs: 23

HOLEID: 1
Comminution:

    HOLEID           X          Y           Z
30       1  556.433037 -521.99913  234.283517

Drill holes:

   HOLEID           X          Y       Z
0       1  559.725175 -513.31032  252.82
1       1  558.955175 -515.23032  246.87
2       1  557.225175 -519.61032  233.37
3       1  555.375175 -524.30032  218.92
4       1  553.825175 -528.21032  206.94

HOLEID: 2
Comminution:

    HOLEID           X          Y          Z
44       2  740.894651 -292.48645  247.78314
45       2  729.079313 -323.26646  161.89374

Drill holes:

    HOLEID           X          Y       Z
15       2  745.345175 -280.60032  280.94
16       2  741.865175 -288.97032  257.64
17       2  738.305175 -297.31032  234.34
18       2  734.705175 -305.65032  211.05
19       2  731.415175 -313.15032  190.52

HOLEID: 3
Comminution:

    HOLEID           X         Y           Z
21       3 -315.880095  286.8803  191.313299

Drill holes:

    HOLEID           X          Y       Z
30       3 -304.024825  318.12968  281.09
31       3 -306.424825  311.36968  261.04
32       3 -308.914825  304.69968  241.70
33       3 -311.554825  297.72968  222.02
34       3 -313.374825  293.07968  208.94

HOLEID: 5
Comminution:

    HOLEID           X          Y           Z
31       5  204.138465 -510.99460  287.921741
46       5  196.946520 -529.73025  340.202245
47       5  213.992071 -485.32507  216.292783

Drill holes:

    HOLEID           X          Y       Z
62       5  198.815175 -524.78032  324.65
63       5  200.565175 -520.24032  311.15
64       5  202.425175 -515.44032  296.82
65       5  204.675175 -509.67032  279.67
66       5  205.785175 -506.81032  271.28

HOLEID: 6
Comminution:

    HOLEID           X          Y           Z
32       6  497.191165 -521.52418  289.606528
33       6  503.288976 -505.63884  242.856820
48       6  512.971931 -480.41388  168.621103
49       6  524.615992 -450.08007   79.350304

Drill holes:

    HOLEID           X          Y       Z
71       6  493.605175 -530.83032  317.10
72       6  494.555175 -528.02032  309.03
73       6  495.235175 -525.99032  303.16
74       6  496.795175 -521.30032  289.63
75       6  499.435175 -513.34032  266.61

============================================================
Flotation vs Comminution
Shared HOLEIDs: 21

HOLEID: 1
Flotation:

    HOLEID           X           Y         Z
0        1  552.477467 -532.303740  205.5292
12       1  549.263567 -540.676239  182.1664

Comminution:

    HOLEID           X          Y           Z
30       1  556.433037 -521.99913  234.283517

HOLEID: 2
Flotation:

    HOLEID           X          Y         Z
1        2  745.774899 -279.77297  283.2592
13       2  737.619747 -301.01787  223.9768

Comminution:

    HOLEID           X          Y          Z
44       2  740.894651 -292.48645  247.78314
45       2  729.079313 -323.26646  161.89374

HOLEID: 3
Flotation:

    HOLEID          X          Y           Z
28       3 -306.22738  311.90928  262.633392
29       3 -310.27390  301.10094  231.504330

Comminution:

    HOLEID           X         Y           Z
21       3 -315.880095  286.8803  191.313299

HOLEID: 5
Flotation:

    HOLEID           X           Y         Z
2        5  200.349851 -520.864270  315.4624
14       5  211.149327 -492.730677  236.9576

Comminution:

    HOLEID           X          Y           Z
31       5  204.138465 -510.99460  287.921741
46       5  196.946520 -529.73025  340.202245
47       5  213.992071 -485.32507  216.292783

HOLEID: 6
Flotation:

   HOLEID           X          Y         Z
3       6  494.372077 -528.86816  311.2195
4       6  500.224749 -513.62142  266.3491
5       6  506.353202 -497.65626  219.3645
6       6  509.539998 -489.35437  194.9325

Comminution:

    HOLEID           X          Y           Z
32       6  497.191165 -521.52418  289.606528
33       6  503.288976 -505.63884  242.856820
48       6  512.971931 -480.41388  168.621103
49       6  524.615992 -450.08007   79.350304